package apodrating

const val API_AUTH_KEY = "ApiKeyAuth"

const val LOCATION_HEADER = "Location"

const val API_KEY_HEADER = "X-API-KEY"

const val STATIC_PATH = "/ui/*"

const val CACHE_ALIAS = "apodCache"

const val CIRCUIT_BREAKER_NAME = "apod-circuit-breaker"

const val HEAP_POOL_SIZE = 10L

const val FIELD_TITLE = "title"
const val FIELD_ID = "id"
const val FIELD_RATING = "rating"
const val FIELD_DATE_STRING = "dateString"
const val FIELD_DATE = "date"
const val FIELD_NASA_API_KEY = "nasaApiKey"
const val PARAM_API_KEY = "api_key"
const val PARAM_HD = "hd"

const val RATING_SERVICE_ADDRESS = "rating_service.apod"
const val REMOTE_PROXY_SERVICE_ADDRESS = "remote-proxy-service.apod"
const val APOD_QUERY_ADDRESS = "apod_query_service.apod"

val STATEMENTS = listOf(
    "CREATE TABLE APOD (ID INTEGER IDENTITY PRIMARY KEY, DATE_STRING VARCHAR(16))",
    "CREATE TABLE RATING (ID INTEGER IDENTITY PRIMARY KEY, VALUE INTEGER, APOD_ID INTEGER, " +
        "FOREIGN KEY (APOD_ID) REFERENCES APOD(ID))",
    "INSERT INTO APOD (DATE_STRING) VALUES '2019-01-10'",
    "INSERT INTO APOD (DATE_STRING) VALUES '2018-07-01'",
    "INSERT INTO APOD (DATE_STRING) VALUES '2017-01-01'",
//                "INSERT INTO APOD (DATE_STRING) VALUES '2016-01-01'",
//                "INSERT INTO APOD (DATE_STRING) VALUES '2015-01-01'",
//                "INSERT INTO APOD (DATE_STRING) VALUES '2019-02-01'",
//                "INSERT INTO APOD (DATE_STRING) VALUES '2019-02-02'",
//                "INSERT INTO APOD (DATE_STRING) VALUES '2019-02-03'",
//                "INSERT INTO APOD (DATE_STRING) VALUES '2017-07-01'",
//                "INSERT INTO APOD (DATE_STRING) VALUES '2012-06-12'",
    "INSERT INTO RATING (VALUE, APOD_ID) VALUES 8, 0",
    "INSERT INTO RATING (VALUE, APOD_ID) VALUES 5, 1",
    "INSERT INTO RATING (VALUE, APOD_ID) VALUES 7, 2",
    "INSERT INTO RATING (VALUE, APOD_ID) VALUES 8, 0",
    "INSERT INTO RATING (VALUE, APOD_ID) VALUES 5, 1",
    "INSERT INTO RATING (VALUE, APOD_ID) VALUES 7, 2",
    "ALTER TABLE APOD ADD CONSTRAINT APOD_UNIQUE UNIQUE(DATE_STRING)"
)
