FROM azul/zulu-openjdk-alpine:12
ARG APODRATING_PORT_ARG
ENV APODRATING_PORT=${APODRATING_PORT_ARG}
ARG APODRATING_H2_PORT_ARG
ENV APODRATING_H2_PORT=${APODRATING_H2_PORT_ARG}
ARG JDBC_URL_ARG
ENV JDBC_URL=${JDBC_URL_ARG}
ARG JDBC_DRIVER_ARG
ENV JDBC_DRIVER=${JDBC_DRIVER_ARG}
ARG JDBC_MAX_POOL_SIZE_ARG
ENV JDBC_MAX_POOL_SIZE=${JDBC_MAX_POOL_SIZE_ARG}
ARG NASA_API_KEY_ARG
ENV NASA_API_KEY=${NASA_API_KEY_ARG}
ARG NASA_API_HOST_ARG
ENV NASA_API_HOST=${NASA_API_HOST_ARG}
ARG NASA_API_PATH_ARG
ENV NASA_API_PATH=${NASA_API_PATH_ARG}
ARG NASA_API_KEY_ARG
ENV NASA_API_KEY=${NASA_API_KEY_ARG}
ARG CACHE_POOL_SIZE_ENTRIES_ARG
ENV CACHE_POOL_SIZE_ENTRIES=${CACHE_POOL_SIZE_ENTRIES_ARG}


EXPOSE 8081
EXPOSE 8443
EXPOSE 5701

### Setup user for build execution and application runtime
ENV APP_ROOT=/opt/app-root
ENV PATH=${APP_ROOT}/bin:${PATH} HOME=${APP_ROOT}
COPY bin/ ${APP_ROOT}/bin/
RUN chmod -R u+x ${APP_ROOT}/bin && \
    chgrp -R 0 ${APP_ROOT} && \
    chmod -R g=u ${APP_ROOT} /etc/passwd

COPY target/dependency-jars /run/dependency-jars
COPY target/application.jar /run/application.jar
### Containers should NOT run as root as a good practice
USER 10001
WORKDIR ${APP_ROOT}

ENTRYPOINT ["java", "-jar", "run/application.jar", "-D", "exec.mainClass=\"apodrating.MainKt\""]
