FROM azul/zulu-openjdk-alpine:11
ARG APODRATING_PORT_ARG
ENV APODRATING_PORT=${APODRATING_PORT_ARG}
ARG APODRATING_H2_PORT_ARG
ENV APODRATING_H2_PORT=${APODRATING_H2_PORT_ARG}
ARG JDBC_URL_ARG
ENV JDBC_URL=${JDBC_URL_ARG}
ARG JDBC_DRIVER_ARG
ENV JDBC_DRIVER=${JDBC_DRIVER_ARG}
ARG JDBC_MAX_POOL_SIZE_ARG
ENV JDBC_MAX_POOL_SIZE=${JDBC_MAX_POOL_SIZE_ARG}
ARG NASA_API_KEY_ARG
ENV NASA_API_KEY=${NASA_API_KEY_ARG}
ARG NASA_API_HOST_ARG
ENV NASA_API_HOST=${NASA_API_HOST_ARG}
ARG NASA_API_PATH_ARG
ENV NASA_API_PATH=${NASA_API_PATH_ARG}
ARG NASA_API_KEY_ARG
ENV NASA_API_KEY=${NASA_API_KEY_ARG}
COPY target/dependency-jars /run/dependency-jars
ADD target/application.jar /run/application.jar

EXPOSE $APODRATING_PORT_ARG:$APODRATING_PORT_ARG
EXPOSE $APODRATING_H2_PORT_ARG:$APODRATING_H2_PORT_ARG

ENTRYPOINT java -jar run/application.jar -D exec.mainClass="apodrating.MainKt"
