FROM azul/zulu-openjdk-alpine:12
ARG APODRATING_PORT_ARG
ENV APODRATING_PORT=${APODRATING_PORT_ARG}
ARG APODRATING_H2_PORT_ARG
ENV APODRATING_H2_PORT=${APODRATING_H2_PORT_ARG}
ARG JDBC_URL_ARG
ENV JDBC_URL=${JDBC_URL_ARG}
ARG JDBC_DRIVER_ARG
ENV JDBC_DRIVER=${JDBC_DRIVER_ARG}
ARG JDBC_MAX_POOL_SIZE_ARG
ENV JDBC_MAX_POOL_SIZE=${JDBC_MAX_POOL_SIZE_ARG}
ARG NASA_API_KEY_ARG
ENV NASA_API_KEY=${NASA_API_KEY_ARG}
ARG NASA_API_HOST_ARG
ENV NASA_API_HOST=${NASA_API_HOST_ARG}
ARG NASA_API_PATH_ARG
ENV NASA_API_PATH=${NASA_API_PATH_ARG}
ARG NASA_API_KEY_ARG
ENV NASA_API_KEY=${NASA_API_KEY_ARG}
ARG CACHE_POOL_SIZE_ENTRIES_ARG
ENV CACHE_POOL_SIZE_ENTRIES=${CACHE_POOL_SIZE_ENTRIES_ARG}
COPY target/dependency-jars /run/dependency-jars
COPY target/application.jar /run/application.jar

EXPOSE 8081
EXPOSE 8443
EXPOSE 5701

ENTRYPOINT ["java", "-jar", "run/application.jar", "-D", "exec.mainClass=\"apodrating.MainKt\""]
